version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: oj
    versions:
    - 3.11.2
    - 3.11.3
    - 3.11.4
  - dependency-name: kramdown
    versions:
    - 2.3.1
  - dependency-name: activesupport
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: unicorn
    versions:
    - 5.8.0
  - dependency-name: money
    versions:
    - 6.14.0
