source 'https://rubygems.org'

gem 'actionview'
gem 'activesupport'
gem 'bundler'
gem 'coveralls', require: false
gem 'dotenv'
gem 'em-http-request'
gem 'em-synchrony'
gem 'eventmachine'
gem 'json'
gem 'kramdown'
gem 'money'
gem 'oj'
gem 'pony'
gem 'rack-test'
gem 'rake-compiler'
gem 'rest-client'
gem 'rest-open-uri'
gem 'rubygems-update'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'unicorn'
